name: Antbuilder Booking - EC2 CI-CD

# Trigger deployment only on push to master branch
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup PM2
      run: npm install -g pm2
    - name: Install App Dependencies
      run: npm install
    - name: Build Nest Application
      run: npm run build
    - name: Start PM2
      run: "pm2 delete --silent antbuilder-booking || :; pm2 start pm2.config.json"